### ISSUE TITLE
Save as URL doesn't work with unicode/emojis

### ISSUE THREAD

**Issue by refset** [xtdb/xt-fiddle#29]
![image](https://github.com/xtdb/xt-fiddle/assets/456658/6285dd4e-19ac-4c39-b148-7cb35d761389)
```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at https://fiddle.xtdb.com/public/js/compiled/app.js:3096:513
    at https://fiddle.xtdb.com/public/js/compiled/app.js:2960:120
    at iu (https://fiddle.xtdb.com/public/js/compiled/app.js:2926:249)
    at mu (https://fiddle.xtdb.com/public/js/compiled/app.js:2928:316)
    at yu (https://fiddle.xtdb.com/public/js/compiled/app.js:2944:38)
    at wu (https://fiddle.xtdb.com/public/js/compiled/app.js:2940:440)
    at https://fiddle.xtdb.com/public/js/compiled/app.js:2942:239
    at xu (https://fiddle.xtdb.com/public/js/compiled/app.js:2943:293)
    at b (https://fiddle.xtdb.com/public/js/compiled/app.js:2940:486)
    at b.port1.onmessage (https://fiddle.xtdb.com/public/js/compiled/app.js:2855:235)
(anonymous) @ app.js:2941
xu @ app.js:2943
yu @ app.js:2944
wu @ app.js:2940
(anonymous) @ app.js:2942
xu @ app.js:2943
b @ app.js:2940
b.port1.onmessage @ app.js:2855
```

**Comment by mpisanko** [comment]
that should now work anyways
